spring.datasource.url=jdbc:postgresql://localhost:5432/PracticeDB
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.mvc.hiddenmethod.filter.enabled=true

# JPA configurations
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

